### ISSUE TITLE
LG TV always ask permission?

### ISSUE THREAD

**Issue by sfanicola** [merdok/homebridge-webos3#5]
Hi! Love your plugin.
Just a question... every time I reboot my raspberry homebridge server, my LG TV asks permission about a remote app and I have to accept it every time to use it on homebridge.
Is there a way to bypass that request on reboot?

When will you implement channel changing? That would be great!!!
Thank you

**Comment by merdok** [comment]
Hi,

I do have that behavior too, but since i rarely reboot my raspberry it wasn't really an issue for me. I suspect that the token get deleted after a reboot and that is why the tv always asks for permissions  again. I will check into it and see if i can fix it.

About the channel changing, this is easy to do and i could make it, but Homekit doesn't support channel changing out of the box so it would have to be done with a light bulb (channels from 1 to 100) and i am not sure if that is the best way. I will look into it deeper.

Greets

**Comment by sfanicola** [comment]
Thanks for answering!
This permission question does not happen with the homebridge lgtv2 plugin.
I'm not a coder but I guess if you integrate the keyfile from that plugin it should work.
Thanks a lot 
Bye

Nicola

**Comment by merdok** [comment]
My latest commit should fix the permission question after each reboot.
