### ISSUE TITLE
[Enhancement] Don't show the Mute icon when setting Volume to 0

### ISSUE THREAD

**Issue by Dexwell** [merdok/homebridge-webos3#8]
When setting the Volume to 0, the Mute icon appears and stays on the screen. This is fine behavior for when _toggling_ the Volume lamp, but I now still have to use the webOS Remote app to set volume to 0 without the icon. (Done by holding Volume Down until 0)

So maybe you can make it so that when HomeKit requests a Volume of 0, you actually send these _two_ commands:

- Set Volume to 1
- Volume Down

**Comment by merdok** [comment]
Will see if i can come up with something for that.

**Comment by Dexwell** [comment]
Another way could be these two, but not sure if that would work:

- Set Volume to 0
- Set Mute state to disabled

**Comment by merdok** [comment]
After analyzing this, i came to the conclusion that this is an issue with the way how the volume is currently represented. I represent it as a light bulb so when you slide it to 0 it automatically mutes the TV and doesn't set the volume, so the mute icon appears. No matter what workaround i do, every time i slide the volume to 0 in the app it will always call the mute action.

I believe this can be fixed with the new Speaker characteristic which was added in iOS11. I will try that out and see if this will output the expected behavior.

**Comment by Dexwell** [comment]
Very clever, totally forgot about the new speaker type.
